# Generated by Django 4.0.4 on 2022-05-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('firstName', models.CharField(blank=True, max_length=15)),
                ('lastName', models.CharField(blank=True, max_length=15)),
                ('nip', models.CharField(blank=True, max_length=10)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('startDate', models.DateField()),
                ('returnDate', models.DateField(blank=True)),
                ('subject', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Outsourced'), (3, 'Complications'), (4, 'Done')], default=1)),
                ('comment', models.TextField(blank=True, max_length=400)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proxifir.client')),
            ],
        ),
    ]
