# Generated by Django 4.0.4 on 2022-05-25 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxifir', '0002_client_coopdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='startDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
