# Generated by Django 4.0.4 on 2022-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxifir', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[('1', 'Przyjete'), ('2', 'outsourcowane'), ('3', 'komplikacje'), ('4', 'wykonane'), ('5', 'oddane')], default=1),
        ),
    ]
