# Generated by Django 3.2.5 on 2022-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxifir', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
