# Generated by Django 3.2.5 on 2022-06-04 15:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proxifir', '0009_alter_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coopDate',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 4, 15, 58, 3, 1048, tzinfo=utc)),
        ),
    ]
