# Generated by Django 3.2.5 on 2022-06-04 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proxifir', '0012_alter_client_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coopDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
